### ISSUE TITLE
firebase admin database url wrong check

### ISSUE THREAD

**Issue by Halo07** [firebase/firebase-admin-python#519] opened 2020-12-16 09:05 UTC
* Operating System version: windows 10
  * Firebase SDK version: 4.5.0
  * Python version: 3.8
  * Firebase Product: database 

Realtime database end with "firebasedatabase.app" and in the "db.py" at line 834 is: 
`        if parsed_url.netloc.endswith('.firebaseio.com'):
            return cls._parse_production_url(parsed_url, emulator_host)`

This return the error: "Database URL must be a valid URL to a Firebase Realtime Database instance" even if you use the right link of the Realtime Database

**Comment by lahirumaramba** [comment] 2020-12-16 18:46
Duplicate of #514 
Fixed by #517

**Closed by lahirumaramba** 2020-12-16 18:46 UTC
Labels: api: database, type: duplicate
