### ISSUE TITLE
facing issues when trying to install firebase-admin in my existing project, after installing also it's throwing error.

### ISSUE THREAD

**Issue by ghost** [firebase/firebase-admin-python#721] opened 2023-09-23 06:05 UTC
I am also getting issues related to pip/trying to run while trying to install **pip install firebase-admin**. Not able to use firebase-admin. Its not install in my existing project.
File "C:\Users\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'firebase_auth'

Below error getting when instilling latest version of firebase-admin:

copying src\cryptography\hazmat\bindings\_rust\openssl\x448.pyi -> build\lib.win-amd64-cpython-37\cryptography\hazmat\bindings\_rust\openssl
  running build_ext
  running build_rust

      =============================DEBUG ASSISTANCE=============================
      If you are seeing a compilation error please try the following steps to
      successfully install cryptography:
      1) Upgrade to the latest pip and try again. This will fix errors for most
         users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
      2) Read https://cryptography.io/en/latest/installation/ for specific
         instructions for your platform.
      3) Check our frequently asked questions for more information:
         https://cryptography.io/en/latest/faq/
      4) Ensure you have a recent Rust toolchain installed:
         https://cryptography.io/en/latest/installation/#rust

      Python: 3.7.3
      platform: Windows-10-10.0.22621-SP0
      pip: n/a
      setuptools: 68.0.0
      setuptools_rust: 1.7.0
      rustc: n/a
      =============================DEBUG ASSISTANCE=============================

  error: can't find Rust compiler

  If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

  To update pip, run:

      pip install --upgrade pip

  and then retry package installation.

  If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs/) is the recommended way to download and update the Rust compiler toolchain.

  This package requires Rust >=1.56.0.

  ----------------------------------------
  Failed building wheel for cryptography
  Running setup.py clean for cryptography
Failed to build cryptography
Could not build wheels for cryptography which use PEP 517 and cannot be installed directly

![image](https://github.com/firebase/firebase-admin-python/assets/144816642/d6f415ad-d8f8-441c-93c3-3527b6889369)

**Comment by lahirumaramba** [comment] 2023-10-04 16:19
Duplicate of #722

**Closed by lahirumaramba** 2023-10-04 16:19 UTC
Labels: needs-triage
