### ISSUE TITLE
is realtime event listening for firebase_admin.firestore possible ?

### ISSUE THREAD

**Issue by amitSA** [firebase/firebase-admin-python#225] opened 2018-11-28 04:02 UTC
#### Environment
  * Operating System version: Ubuntu 16 LTS
  * Firebase SDK version: 
    - firebase-admin=2.13.0
    - google-cloud-firestore=0.30.0
  * Library version: ? not sure
  * Firebase Product: firestore

#### Description:
Will listening for realtime events on collections be implemented for firestore python ? 
Some documentation indicates that it's possible, yet other documentation and my own testing indicates else wise. 

#### Details
The documentation for [CollectionReference](https://googleapis.github.io/google-cloud-python/latest/firestore/collection.html#google.cloud.firestore_v1beta1.collection.CollectionReference.on_snapshot) indicates that `on_snapshot` can be used to register event listeners on collections. 

However, this [firestore tutorial](https://firebase.google.com/docs/firestore/query-data/listen) is saying that `"Note: Realtime listeners are not supported in Python and PHP."`.   So there are two contradictory sources
Furthermore, in my own tests I'm getting that `on_snapshot` is not an attribute of an `CollectionReference`, suggestion that this feature is not possible. 
 
Can you confirm whether realtime listening in python firestore admin sdk is possible or not ?

#### Relevant Code:
The documentation for `on_snapshot` says this code should work
```
    from google.cloud import firestore
    db = firestore.Client()
    collection_ref = db.collection(u'users')
    def on_snapshot(collection_snapshot):
        for doc in collection_snapshot.documents:
            print(u'{} => {}'.format(doc.id, doc.to_dict()))
     collection_watch = collection_ref.on_snapshot(on_snapshot)
```
However it's giving me an error 
`AttributeError: 'CollectionReference' object has no attribute 'on_snapshot'`

**Comment by hiranya911** [comment] 2018-11-30 22:40
Duplicate of https://stackoverflow.com/questions/53511983/is-realtime-event-listening-for-firebase-admin-firestore-possible

**Closed by hiranya911** 2018-11-30 22:40 UTC
