### ISSUE TITLE
auth.create_session_cookie throws exception when expires_in argument is provided

### ISSUE THREAD

**Issue by nketia** [firebase/firebase-admin-python#552] opened 2021-05-07 14:14 UTC
**Please help with this issue.**

auth.create_session_cookie(custom_token, expires_in) TypeError: create_session_cookie() takes 1 positional argument but 2 were given. Below is my code

custom_token = flask.request.headers.get('Authorization')
            expires_in = datetime.timedelta(days=5)
            print(expires_in) # 5 days, 0:00:00
            session_cookie = auth.create_session_cookie(custom_token, expires_in)

File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app response = self.full_dispatch_request() File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1953, in full_dispatch_request return self.finalize_request(rv) File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1970, in finalize_request response = self.process_response(response) File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 2267, in process_response response = handler(response) File

**Comment by hiranya911** [comment] 2021-05-07 19:29
Doesn't reproduce to us. Following code woks as expected:

```py
import datetime
import firebase_admin
from firebase_admin import auth
from firebase_admin import credentials
import flask
from flask import Flask

app = Flask(__name__)

firebase_admin.initialize_app(
  credential=credentials.Certificate('../public/cert.json')
)

@app.route('/')
def hello_world():
  custom_token = flask.request.headers.get('Authorization')
  expires_in = datetime.timedelta(days=5)
  print(expires_in) # 5 days, 0:00:00
  session_cookie = auth.create_session_cookie(custom_token, expires_in)
  return 'Hello, World!'
```

Can you provide a minimal repro for us to test?

**Comment by hiranya911** [comment] 2021-05-27 22:48
Closing this due to lack of information.

**Closed by hiranya911** 2021-05-27 22:48 UTC
Labels: needs-triage
