### ISSUE TITLE
__init__() got unexpected argument 'status'

### ISSUE THREAD

**Issue by Nim1304** [firebase/firebase-admin-python#479] opened 2020-07-30 19:03 UTC
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Debian (bullseye)
  * Firebase SDK version: 4.3.0
  * Library version: 4.3.0
  * Firebase Product: auth 

### [REQUIRED] Step 3: Describe the problem
  import firebase_admin
  from firebase_admin import auth

This always throws the Error : 

Traceback (most recent call last):
  File "driver.py", line 14, in <module>
    from firebase_admin import credentials, firestore, storage, auth
  File "/usr/local/lib/python3.8/dist-packages/firebase_admin/auth.py", line 22, in <module>
    from firebase_admin import _auth_client
  File "/usr/local/lib/python3.8/dist-packages/firebase_admin/_auth_client.py", line 22, in <module>
    from firebase_admin import _http_client
  File "/usr/local/lib/python3.8/dist-packages/firebase_admin/_http_client.py", line 30, in <module>
    DEFAULT_RETRY_CONFIG = retry.Retry(
TypeError: __init__() got an unexpected keyword argument 'status'

#### Steps to reproduce:
just try to run the above code...even importing throws err.

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:
```
import firebase_admin
from firebase_admin import credentials, firestore, storage, auth
```

**Comment by hiranya911** [comment] 2020-07-30 19:06
Duplicate of #262

**Closed by hiranya911** 2020-07-30 19:06 UTC
Labels: api: auth

**Comment by hamidsafiullah** [comment] 2022-09-22 04:34
made changes to _http_client.py python file by removing status on 37 line
