### ISSUE TITLE
firebase-admin breaks chalice deployment in github workflows

### ISSUE THREAD

**Issue by apfromiit** [firebase/firebase-admin-python#656] opened 2022-10-18 12:54 UTC
### [READ] Step 1: Are you in the right place?

  * For issues related to __the code in this repository__ file a GitHub issue.
  * If the issue pertains to __Cloud Firestore__, report directly in the
    [Python Firestore](https://github.com/googleapis/python-firestore) GitHub repo. Firestore
    bugs reported in this repo will be closed with a reference to the Python Firestore
    project.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: ubuntu-latest in github workflows
  * Firebase SDK version: 6.0.1
  * Firebase Product: firebase-admin python sdk
  * Python version: Python 3.8.10
  * Pip version: pip 20.0.2

#### Steps to reproduce:

Repo: https://github.com/apfromiit/chalice-firebase-admin-issue
The above repo has a new chalice project and a github workflow to deploy it to aws account.

The github workflow fails. Refer the failure logs in below link.
https://github.com/apfromiit/chalice-firebase-admin-issue/actions

requirements.txt contains firebase-admin only

The issue may not be reproducible in local machines

#### Relevant Code:

requirements.txt: https://github.com/apfromiit/chalice-firebase-admin-issue/blob/main/requirements.txt

Github Workflow: https://github.com/apfromiit/chalice-firebase-admin-issue/blob/main/.github/workflows/chalice-deploy.yml

**Comment by lahirumaramba** [comment] 2022-10-18 21:04
Hi @apfromiit Thank you for the repro! This looks like an `openssl` issue. Are you able to upgrade `pyOpenSSL` in your environment? Also see: https://askubuntu.com/questions/1428181/module-lib-has-no-attribute-x509-v-flag-cb-issuer-check

**Comment by apfromiit** [comment] 2022-10-19 03:54
Upgrading pyOpenSSL to latest version solved the issue. Thanks for the workaround.

https://github.com/apfromiit/chalice-firebase-admin-issue/commit/e307ac7eb9d244c8dedbf3eefca98aa7081c6f45?diff=unified

But adding pyJWT to the requirements also solved the issue.

https://github.com/apfromiit/chalice-firebase-admin-issue/blob/main/requirements.txt

Then is the below recent code change in firebase-admin Release 6.0.1 the actual root cause for this breakage?

https://github.com/firebase/firebase-admin-python/commit/37ecf18d0ad09d7402143f22443e957a57ec7a2a

**Comment by lahirumaramba** [comment] 2022-10-19 17:42
Ah that could be it. `pyJWT` was not added to the distribution artifacts and we fixed that in `6.0.1`. Could you check if the issue is solved if you use the latest `firebase-admin` release, please? Thank you!

**Comment by apfromiit** [comment] 2022-10-19 23:27
The actual issue reported was based on latest version: 6.0.1

The issue is not happening with firebase-admin==6.0.0
The issue occurs with firebase-admin==6.0.1

<img width="1043" alt="Screenshot 2022-10-20 at 4 56 51 AM" src="https://user-images.githubusercontent.com/5106676/196823130-62ee6bbf-3297-475f-b6a8-39a3e7d18dff.png">

**Comment by lahirumaramba** [comment] 2022-11-11 22:23
Since upgrading `pyOpenSSL` fixed the issue I am going to close this. We can reopen later if needed. Thanks!

**Closed by lahirumaramba** 2022-11-11 22:23 UTC
Labels: needs-triage
