### ISSUE TITLE
Error in loading db module from firebase_admin: "...unexpected arguement 'status'"

### ISSUE THREAD

**Issue by russellromney** [firebase/firebase-admin-python#262] opened 2019-02-12 15:09 UTC
Environment:
  * OS X 10.14.3
  * firebase-admin 2.15.1
  * python 3.6.7 with Anaconda

#### Steps to reproduce:

`from firebase_admin import db`

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-28-f1634322845c> in <module>
----> 1 from firebase_admin.db import Query

~/anaconda3/lib/python3.6/site-packages/firebase_admin/db.py in <module>
     31 
     32 import firebase_admin
---> 33 from firebase_admin import _http_client
     34 from firebase_admin import _sseclient
     35 from firebase_admin import _utils

~/anaconda3/lib/python3.6/site-packages/firebase_admin/_http_client.py in <module>
     28 DEFAULT_RETRY_CONFIG = retry.Retry(
     29     connect=1, read=1, status=4, status_forcelist=[500, 503],
---> 30     raise_on_status=False, backoff_factor=0.5)
     31 
     32 

TypeError: __init__() got an unexpected keyword argument 'status'
```

I've tried this in a jupyter notebook and in the inline client. Someone else has the error on [stackoverflow as well](https://stackoverflow.com/questions/54644641/unable-to-import-database-module-from-firebase-admin#_=_)

**Comment by hiranya911** [comment] 2019-02-12 21:31
Duplicate of #260

Your runtime is picking up an old version of urllib3. You can check which version gets picked by running:

```
>>> import requests
>>> from requests.packages import urllib3
>>> urllib3.__version__
'1.24.1'
```

**Closed by hiranya911** 2019-02-12 21:31 UTC
Labels: needs-triage

**Comment by xujenna** [comment] 2019-02-13 01:03
@hiranya911 I'm having the same issue, and my version of urllib3 is up-to-date. Furthermore, the ```__init___``` method doesn't accept an argument ```'status'```.

**Comment by hiranya911** [comment] 2019-02-13 01:17
I just commented on Stackoverflow. `Retry.__init__()` definitely accepts a status parameter. It has supported that argument since 1.21.0 release which went out in 2017.

Code from the v1.21.0 release tag: https://github.com/urllib3/urllib3/blob/1.21/urllib3/util/retry.py#L152
Pull request that implemented the `status` feature from 2017: https://github.com/urllib3/urllib3/pull/1148

You may have a recent version of urllib3 installed in the system, but that's not what your Python code/runtime picks up.

**Comment by hiranya911** [comment] 2019-02-13 01:18
Try running the following as part of your program somewhere and see what happens:

```
import requests
from requests.packages import urllib3
print(urllib3.__version__)
```

**Comment by xujenna** [comment] 2019-02-13 01:48
Thanks @hiranya911 ! You're right, ```print(urllib3.__version__)``` returns ```1.20```, apparently because that specific ```urllib3``` package, located inside the ```requests``` package, is out of date. The ```urllib3``` package I've been upgrading like a crazy person is the standalone one outside of ```requests```. 

However, I've tried upgrading the ```requests``` module as well, but this doesn't seem to upgrade its version of ```urllib3```. Please advise 🙏

**Comment by hiranya911** [comment] 2019-02-13 05:11
@xujenna  `requests` doesn't ship with `urllib3` either. It just gets wired up to a `urllib3` installation already present in the system. So somewhere in your environment there's a `urllib3` 1.20 already installed. You can do the following to see where it is installed:

```
import requests
from requests.packages import urllib3
print(urllib3.__file__)
```

Once you know where it's coming from perhaps you will be able to get rid of it, or figure out a way to upgrade it.

**Comment by xujenna** [comment] 2019-02-13 06:15
@hiranya911 Thank you so much!! This has been torturing me for days.

**Comment by russellromney** [comment] 2019-02-13 09:42
@hiranya911 thank you very much! I had tried updating `requests` with `pip` and with `conda` but it had not worked. I used `conda update urllib3` and restarting my Jupyter kernels.

**Comment by michaelspring** [comment] 2019-06-12 14:52
@xujenna Hi! Did you manage to find a way to upgrade or replace the v1.20.0 once you found it?

**Comment by xujenna** [comment] 2019-06-12 16:57
@michaelspring haha I ended up just removing the old ```urllib3``` from ```requests```

**Comment by eagalvez** [comment] 2019-11-17 22:35
I have already removed urllib3 from request packages but I still have the problem with the old version and when I run this code
`import requests
from requests.packages import urllib3
urllib3.__file__`
urllib3 appears me the same location despite of the files doesn't exist already. What do you think is the error? please help me

**Comment by noahastern** [comment] 2020-02-03 03:07
To solve this, I manually installed requests to the latest version before installing firebase_admin. This way, requests already had the latest version of urllib3 and it was able to run just fine.

**Comment by Atsushi-Koyama** [comment] 2020-04-14 09:10
@noahastern Thank you so much!

**Comment by kirankbee** [comment] 2022-05-17 22:23
the issue surfaced again with the pyrebase , requests, and request-toolbelt conflicts.\
Uninstalled urlib3, requests, & request-toolbelt 
pip3 install requests-toolbelt>=0.7.0
pip3 install requests>=2.27.1
but the problem resurfaced with conflict of tensorboard 
OS : ubuntu
