### ISSUE TITLE
Firestore listener stops receiving changes after a long time running without throwing an error

### ISSUE THREAD

**Issue by AndersonHappens** [firebase/firebase-admin-python#294] opened 2019-05-31 15:48 UTC
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Windows 10
  * Firebase SDK version: 6.10.0
  * Library version: firebase-admin: 2.16.0
  * Firebase Product: firestore 

#### Steps to reproduce:

After running a firebase listener for a long time (4-14) days and restarting the listener every time it closes due to the other issue, (https://github.com/firebase/firebase-admin-python/issues/282), eventually the listener will stop receiving changes all together. This is not the internet connection issue (https://github.com/firebase/firebase-admin-python/issues/287) as I tried testing it after an internet disconnection for 1 minute and both listeners kept receiving changes and after 5 minutes both listeners I had running restarted due to "None stream".

I have tried debugging the listener after it stops working, but the _closed variable is still false and all other class variables are still normal (is_active is true, had_pushed is true). It seems to be random chance though, because of the two listeners I have, one of them never stops receiving changes while the other one will after a long time. The only real difference I have between the two is that I call time.sleep in the one that stops receiving input and I don't in the other listener. I will keep debugging and see if that's the issue, but I doubt it.

#### Relevant Code:

The code has the same structure as this:
```
class TestWatchInfo():
  def __init__(self):
    self.start_snapshot()

  def start_snapshot(self):
    self.query_watch = db.collection(u'info').on_snapshot(self.on_snapshot)

  def on_snapshot(self, col_snapshot, changes, read_time):
    try:
      for change in changes:
        # do lots of stuff here that can take up to a minute to complete
        # including writes, deletes, and reads from the database
        time.sleep(60)
    except Exception as err:
      print(err)
      print("Error occurred at " + str(time.ctime()))
      traceback.print_exc()

if __name__ == '__main__':
  try:
    test_object = TestWatchInfo()
    while(True):
      if test_object.query_watch._closed:
        test_object.start_snapshot()
      # code here
  except Exception as err:
    print(err)
    print("Error occurred at " + str(time.ctime()))
    traceback.print_exc()
```

**Comment by AndersonHappens** [comment] 2019-05-31 16:10
I'm pretty sure that sleep isn't the issue. It works normally in the snapshot. Firestore will still catch changes that are made consecutively while the thread is sleeping and will wait for the thread to finish before updating the next changes just fine. I also tested updating firestore while both the main thread and the snapshot thread were paused in a debugger (to simulate them sleeping simultaneously) and it caught the updates just fine and continued to run. The annoying part about this bug is that there are no logs or errors thrown anywhere for me to check and debug - the listener just stops receiving updates (I check by seeing if the listener propagates those updates to other parts of the firestore database)

**Comment by hiranya911** [comment] 2019-05-31 20:32
@tseaver @BenWhitehead can you take a look?

**Comment by AndersonHappens** [comment] 2019-06-17 22:56
Status update on this? I'm just manually restarting the listener every hour to get around this currently.

**Comment by BenWhitehead** [comment] 2019-06-17 23:11
@crwilcox Any insight you might be able to add here? This is out of my depth.

**Comment by eambutu** [comment] 2019-07-09 01:41
I get this bug too: the listener just stops getting changes and the .closed flag is still false. One thing I've noticed is that when I restart the server, all the changes it missed come in at once. Right now our workaround is to use a cron job to restart the server every hour, but it would be nice to know the actual fix to this.

**Comment by linevych** [comment] 2019-09-27 09:45
I have the same issue and used the same workaround. I have a thread that checks `watch._closed` in the infinite loop every 0.1 second. Any update on when this will be fixed?

**Comment by MilkyWayGalaxyUser** [comment] 2020-08-04 14:42
same ISSUE!

**Comment by doylep** [comment] 2020-08-25 19:15
Writing to confirm that this issue is still out in the wild. Is there a recommended workaround?

**Comment by BenWhitehead** [comment] 2020-08-25 19:25
Ongoing work to figure out the root cause of this issues is happening over on https://github.com/googleapis/python-firestore/issues/18. As of now, there is not a known reliable work around.

**Comment by doylep** [comment] 2020-08-25 19:45
Thanks for the update. I will resort to restarting the call every minute for now.

**Comment by schmidt-sebastian** [comment] 2020-08-25 19:56
Closing this as we will continue to track the progress in https://github.com/googleapis/python-firestore/issues/18

**Closed by schmidt-sebastian** 2020-08-25 19:56 UTC
Labels: api: firestore
