### ISSUE TITLE
AndroidNotification.event_timestamp in past 51 years ago when is set

### ISSUE THREAD

**Issue by catalin-florescu** [firebase/firebase-admin-python#534] opened 2021-03-02 16:59 UTC
When sending a multicast notification and setting `event_timestamp` as `event_timestamp=datetime.now()`, in Android notification appears to be in past when received (**51 years ago**). If param is removed from `AndroidConfig`, notification will appear received as **Now**.

  * Operating System version: mac os big sur
  * Firebase SDK version: tested with 4.4.0 and 4.5.2
  * Firebase Product: messaging

```
message = messaging.MulticastMessage(
        notification=messaging.Notification(
            title=title,
            body=body,
            image=image
        ),
        android=messaging.AndroidConfig(
            ttl=timedelta(hours=6),
            priority='high',
            notification=messaging.AndroidNotification(
                icon=icon,
                event_timestamp=datetime.now(),
                channel_id=channel_id,
                priority='high'
            )
        ),
        tokens=registration_tokens,
    )
response = messaging.send_multicast(message)
```

![Screenshot 2021-03-02 at 18 43 51](https://user-images.githubusercontent.com/7399214/109683455-08e62000-7b88-11eb-9a1e-37435bd22af5.png)

**Comment by lahirumaramba** [comment] 2021-03-02 17:22
Hi @catalin-florescu!
Just FYI, the `event_timestamp` in `AndroidNotification` converts a `naive` `datetime` instance to UTC timezone.. though I doubt that could be the problem in your case. To further investigate this issue could you try the following, please?

In your code, try logging the result of `datetime.now()`.
```
now = datetime.datetime.now()
print(now.year, now.month, now.day, now.hour, now.minute, now.second)
```
Additionally, you can create a date time `aware` instance (with a timezone) and check the result.
```
event_timestamp=datetime.datetime(
                        2021, 3, 2, 15, 12, 23, 123,
                        tzinfo=datetime.timezone(datetime.timedelta(hours=-5))
                    )
```

**Comment by catalin-florescu** [comment] 2021-03-02 17:48
Hi @lahirumaramba, thanks for your quick replay.

The output of 
```
now = datetime.datetime.now()
print(now.year, now.month, now.day, now.hour, now.minute, now.second)
```
is
```
2021 3 2 19 44 18
```
so this can't be problem.

Creating an aware datetime instance with any configuration (even set in future) gives me the same result, 51 years ago.

**Comment by lahirumaramba** [comment] 2021-03-02 17:58
Thank you for confirming the output of `datetime.now()` @catalin-florescu 

@chong-shao do you have any ideas on what might be going on here? :)

**Comment by catalin-florescu** [comment] 2021-03-05 09:13
I'm thinking that could be an Android problem, is not singular [(see here)](https://stackoverflow.com/questions/59560153/fcm-in-android-notification-payload-event-time).

Firebase admin is sending correct date. Also tried using Google PlayGround and Postman and the same error, received ```event_timestamp``` is converted to start of UNIX time.

**Comment by hiranya911** [comment] 2021-03-12 23:32
@chong-shao can you please take a look when you get a chance?

**Comment by hiranya911** [comment] 2021-03-19 23:50
@chong-shao do you have any updates? I believe some fixes are being made in the backend to address this issue? If so may be we can reference the internal issue number and resolve this.

**Comment by chong-shao** [comment] 2021-03-20 00:02
We identified the cause of the problem with the event_time field. The fix has been implemented and verified. The expected fix deployment time is mid next week.

**Comment by chong-shao** [comment] 2021-03-24 02:53
The fix has been deployed in the backend. @catalin-florescu please let us know whether the issue is still occurring on your end. Thanks!

**Comment by chong-shao** [comment] 2021-03-24 18:19
Close since we verified the fix on backend on our side. Feel free to close if the issue still exists on your side. Thanks!

**Closed by chong-shao** 2021-03-24 18:19 UTC
Labels: api: messaging

**Comment by catalin-florescu** [comment] 2021-03-29 17:47
@chong-shao now is working. Thanks for your help. Sorry for late answer.
