### ISSUE TITLE
FR: Support device group

### ISSUE THREAD

**Issue by WouterHouwen** [firebase/firebase-admin-python#191] opened 2018-08-10 10:14 UTC
For cloud-messaging, I want to have a feature to manage and send messages to device groups.

**Comment by enver** [comment] 2018-11-02 19:17
@hiranya911 It seems to be supported now: https://firebase.google.com/docs/cloud-messaging/android/device-group

**Comment by aksswami** [comment] 2019-01-02 03:59
@hiranya911 Device group messaging seems to be supported now, can we have some update on this?

**Comment by hiranya911** [comment] 2019-01-02 19:35
The new FCM API doesn't support device groups: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages

Only the legacy API does: https://firebase.google.com/docs/cloud-messaging/http-server-ref

I don't think there are any plans to support device groups in the new FCM API at the moment. But we are exploring alternatives for supporting token-based multicast support in FCM.

**Comment by chong-shao** [comment] 2019-02-05 22:37
Hi, the FCM team is working on a new private topics feature for Java Admin SDK, which would be equivalent to device groups.

**Comment by chong-shao** [comment] 2019-02-07 21:59
This is also mentioned in https://github.com/firebase/firebase-admin-java/issues/187. Will close this issue.

**Closed by chong-shao** 2019-02-07 21:59 UTC
Labels: component: messaging

**Comment by holocronweaver** [comment] 2023-09-28 03:26
Please re-open so that the issue is tracked for the Python SDK specifically. This is to avoid ending up with the same situation as before where only the node SDK supported device groups and none other.

Or else update firebase/firebase-admin-java#187 to include a list of the SDKs to be updated.

As far as I can tell the private topics feature was never released, and device groups still don't have great support five years later. :disappointed:
