### ISSUE TITLE
TransportError when running within App Engine

### ISSUE THREAD

**Issue by rjvir** [firebase/firebase-admin-python#46] opened 2017-07-06 21:00 UTC
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: MacOS Sierra (10.12.4)
  * Firebase SDK version: 2.1.0
  * Library version: N/A
  * Firebase Product: Firebase Admin Python

#### Steps to reproduce:

1. Set up a Google App Engine environment (Python 2.7). Add SSL as a library in app.yaml
2. Write code for a trivial DB transaction
3. Run this code in the development app engine environment (eg `dev_appserver.py app.yaml`)

Running a trivial DB write results in this error message:

```
Traceback (most recent call last):
  File "/Users/rajvir/Dev/SR-backend/scraper.py", line 289, in firebase_test
    'test': 'value'
  File "/Users/rajvir/Dev/SR-backend/lib/firebase_admin/db.py", line 152, in set
    self._client.request_oneway('put', self._add_suffix(), json=value, params='print=silent')
  File "/Users/rajvir/Dev/SR-backend/lib/firebase_admin/db.py", line 603, in request_oneway
    self._do_request(method, urlpath, **kwargs)
  File "/Users/rajvir/Dev/SR-backend/lib/firebase_admin/db.py", line 631, in _do_request
    resp = self._session.request(method, self._url + urlpath, auth=self._auth, **kwargs)
  File "/Users/rajvir/Dev/SR-backend/lib/requests/sessions.py", line 488, in request
    prep = self.prepare_request(req)
  File "/Users/rajvir/Dev/SR-backend/lib/requests/sessions.py", line 431, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/rajvir/Dev/SR-backend/lib/requests/models.py", line 309, in prepare
    self.prepare_auth(auth, url)
  File "/Users/rajvir/Dev/SR-backend/lib/requests/models.py", line 540, in prepare_auth
    r = auth(self)
  File "/Users/rajvir/Dev/SR-backend/lib/firebase_admin/db.py", line 674, in __call__
    req.headers['Authorization'] = 'Bearer {0}'.format(self._app._get_token())
  File "/Users/rajvir/Dev/SR-backend/lib/firebase_admin/__init__.py", line 211, in _get_token
    self._token = self._credential.get_access_token()
  File "/Users/rajvir/Dev/SR-backend/lib/firebase_admin/credentials.py", line 97, in get_access_token
    self._g_credential.refresh(_request)
  File "/Users/rajvir/Dev/SR-backend/env/lib/python2.7/site-packages/google/oauth2/service_account.py", line 310, in refresh
    request, self._token_uri, assertion)
  File "/Users/rajvir/Dev/SR-backend/env/lib/python2.7/site-packages/google/oauth2/_client.py", line 143, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/Users/rajvir/Dev/SR-backend/env/lib/python2.7/site-packages/google/oauth2/_client.py", line 104, in _token_endpoint_request
    method='POST', url=token_uri, headers=headers, body=body)
  File "/Users/rajvir/Dev/SR-backend/env/lib/python2.7/site-packages/google/auth/transport/requests.py", line 115, in __call__
    raise exceptions.TransportError(exc)
TransportError: ('Connection aborted.', error(13, 'Permission denied'))
```

Running this same code outside of the App Engine environment works normally as expected. 

#### Relevant Code:

```

cred = credentials.Certificate('service_account_file.json')
firebase_admin.initialize_app(cred, {
    'databaseURL': 'https://APP_ID.firebaseio.com'
})
ref = db.reference()

def firebase_test():
    try:
        ref.set({
            'test': 'value'
        })
    except:
        traceback.print_exc()
```

**Comment by hiranya911** [comment] 2017-07-06 23:33
I believe this is the expected behavior. The requests library is known to not work on App Engine dev app server. On production you need to enable billing for it to work. See https://stackoverflow.com/questions/9604799/can-python-requests-library-be-used-on-google-app-engine

**Comment by rjvir** [comment] 2017-07-06 23:54
Thanks. 

Then maybe a feature request would be for this library to work on the App Engine dev app server. I think this would be very helpful for developers, myself included. 

The monkeypatch described in [this](https://stackoverflow.com/a/37304524) answer seems like a simple solution and is recommended by Google, and it's one I've used myself with success.

**Comment by hiranya911** [comment] 2017-07-07 00:07
The monkeypatch is the recommended solution, but it should be done in the main.py of the web app. This cannot be built into the Admin SDK. As for supporting the dev app server, that's really a bug in dev appserver code.

**Comment by hiranya911** [comment] 2017-07-07 01:53
I've created an [issue](https://github.com/GoogleCloudPlatform/google-auth-library-python/issues/169) for the google-auth library documenting some of the pain points related to App Engine support. Hopefully we can get some useful feedback from them.

As for the poor support from the dev appserver, this is a long running issue and many other projects are experiencing the same problem. However, there are several workarounds. For me adding the following bit of code into the `appengine_config.py`solved the issue:

```
import os
import google
import imp
import inspect
from google.appengine.ext import vendor

from google.appengine.tools.devappserver2.python import sandbox
sandbox._WHITE_LIST_C_MODULES += ['_ssl', '_socket']

runtime_path = os.path.realpath(inspect.getsourcefile(inspect))
runtime_dir = os.path.dirname(runtime_path)

# Patch and reload the socket module implementation.
system_socket = os.path.join(runtime_dir, 'socket.py')
imp.load_source('socket', system_socket)

# Patch and reload the ssl module implementation.
system_ssl = os.path.join(runtime_dir, 'ssl.py')
imp.load_source('ssl', system_ssl)
```

This basically whitelists the `socket` and `ssl` libraries for the dev app server, and uses the system-level socket library instead of the one packaged with the App Engine SDK. Your mileage may vary.

**Comment by hiranya911** [comment] 2017-07-07 01:55
I will close this issue, since there's not much we can do from our end to resolve the issues discussed here. We can continue to follow up with the Google cloud and google-auth team to get these issues addressed in the long run.

**Closed by hiranya911** 2017-07-07 01:55 UTC

**Comment by titocosta** [comment] 2018-10-30 04:51
Just updated to Google App Engine Python 1.9.77 which raises an exception when importing sandbox.
Therefore the workaround suggested above stopped working.
