### ISSUE TITLE
Requested entity was not found

### ISSUE THREAD

**Issue by oluwaseunladeinde** [firebase/firebase-admin-python#180] opened 2018-07-15 22:50 UTC
### Send messages

  * Trying to send a message to an android device with its registration token.
  * I get a 404 all the time 
    * requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://fcm.googleapis.com/v1/projects/project-id/messages:send
   * firebase_admin.messaging.ApiCallError: Requested entity was not found.

### Need help urgently

  * Operating System version: Windows 10
  * Firebase SDK version: firebase-admin-python
  * Library version: Python 3
  * Firebase Product: messaging

#### Steps to reproduce:

Get the token from a registered android device and tried sending message to the same device but kept getting a 404 entity requested not found. I am confused at what entity it is referring to. . I was wondering if I had to save the device token on my firebase db?

**Comment by hiranya911** [comment] 2018-07-17 05:17
The SDK is not detecting your project ID. How did you initialize the SDK? Share the code please.

**Comment by oluwaseunladeinde** [comment] 2018-07-18 18:09
from firebase_admin import credentials, initialize_app, delete_app, auth, db, get_app, \
    messaging

cred = credentials.Certificate('filename.json')
default_app = initialize_app(cred)
message = messaging.Message(data={'note': '2864974004'}, token='<registration token>',)
response = messaging.send(message)

@hiranya911  I suspect that is  the case. But the filename.json was generated from my serviceaccount from the Google API Console.  SO I am not sure how the Project ID is not recognized.

**Comment by hiranya911** [comment] 2018-07-18 18:14
Did you edit the following error message in any way before posting? I see the string `project-id` in the URL, which is not correct:

```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://fcm.googleapis.com/v1/projects/project-id/messages:send
```

If this is indeed the error you receive, then that's the issue.

**Comment by oluwaseunladeinde** [comment] 2018-07-19 23:12
I actually did. It was my attempt to mask my project id. Not sure if it was safe to make that public. 
@hiranya911

**Comment by hiranya911** [comment] 2018-07-20 00:20
Ok, in that case my initial guess was wrong. The SDK does indeed correctly pick up the project ID. Try downloading a service account from Firebase console, and give this another try. I'm thinking this has something to do with how your service account json was obtained.

**Comment by oluwaseunladeinde** [comment] 2018-07-23 00:54
Hi @hiranya911 I get an entirely new error with a new service account generated from the Firebase Console twice. I have enabled Firebase Cloud Messaging API but nothing works. 

** raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://fcm.googleapis.com/v1/projects/project-id/messages:send

** raise ApiCallError(code, msg, error) firebase_admin.messaging.ApiCallError: The caller does not have permission

Do you have a sample codebase that works that I can use as a guide. At this point, its difficult to tell whether  it is  my code or there are some pieces n the setup I have missed. The Python code on th documentation has not helped much. 

Thanks in advance.

**Comment by hiranya911** [comment] 2018-07-23 23:47
The issue doesn't reproduce to me. And since this is the only report we have received on this issue, it's most likely a problem with your environment and project set up. Try capturing the full response payload sent by the back-end server. You can access this via the `detail` property of the `ApiCallError`.

`err.detail.response.json()`

**Comment by joshimbriani** [comment] 2018-08-06 21:39
I had the same error as your initial one and it turned out that my device ID changed and I was still using the old ID. If anyone sees that error in the future it might be worth double checking that you have the correct device token.

**Comment by hiranya911** [comment] 2018-08-17 21:02
I'm closing this  as there aren't enough details to investigate this further. Please let us know if somebody finds something new related to this.

**Closed by hiranya911** 2018-08-17 21:02 UTC

**Comment by Syednazirhussain** [comment] 2018-09-24 12:56
I also faced the same issue if device no longer exists it show me the error like that i actually send bulk notification having device ids inside an array and loop through it when any device id no longer exist it break my code i want to handle and continue to next device id
{
    "message": "Client error: `POST https://fcm.googleapis.com/v1/projects/internationalfriendspusher/messages:send` resulted in a `404 Not Found` response:\n{\n  \"error\": {\n    \"code\": 404,\n    \"message\": \"Requested entity was not found.\",\n    \"status\": \"NOT_FOUND\",\n    \"detail (truncated...)\n",
    "exception": "Kreait\\Firebase\\Exception\\Messaging\\NotFound",
    "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/kreait/firebase-php/src/Firebase/Exception/MessagingException.php",
    "line": 76,
    "trace": [
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/kreait/firebase-php/src/Firebase/Exception/MessagingException.php",
            "line": 51,
            "function": "withResponse",
            "class": "Kreait\\Firebase\\Exception\\MessagingException",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/kreait/firebase-php/src/Firebase/Messaging/ApiClient.php",
            "line": 52,
            "function": "fromRequestException",
            "class": "Kreait\\Firebase\\Exception\\MessagingException",
            "type": "::"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/kreait/firebase-php/src/Firebase/Messaging/ApiClient.php",
            "line": 26,
            "function": "request",
            "class": "Kreait\\Firebase\\Messaging\\ApiClient",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/kreait/firebase-php/src/Firebase/Messaging.php",
            "line": 53,
            "function": "sendMessage",
            "class": "Kreait\\Firebase\\Messaging\\ApiClient",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/app/Http/Controllers/API/PusherAPIController.php",
            "line": 184,
            "function": "send",
            "class": "Kreait\\Firebase\\Messaging",
            "type": "->"
        },
        {
            "function": "store",
            "class": "App\\Http\\Controllers\\API\\PusherAPIController",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
            "line": 54,
            "function": "call_user_func_array"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
            "line": 45,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 212,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 169,
            "function": "runController",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 658,
            "function": "run",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 30,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php",
            "line": 41,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 149,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php",
            "line": 57,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 149,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 102,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 660,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 635,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 601,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 590,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 176,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 30,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/fideloper/proxy/src/TrustProxies.php",
            "line": 56,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 149,
            "function": "handle",
            "class": "Fideloper\\Proxy\\TrustProxies",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 30,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 149,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 30,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 149,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 149,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
            "line": 46,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 149,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 102,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 151,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/MainApp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 116,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/var/www/vhosts/lvps87-230-85-233.dedicated.hosteurope.de/pusherang/index.php",
            "line": 57,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        }
    ]
}

**Comment by vsukhin** [comment] 2018-10-16 15:11
Got an interesting case, we recieved "Requested entity was not found." error for some old device ids, but notification was still delivered to the device

**Comment by zardilior** [comment] 2019-03-28 19:21
Got same error when sending notifications

**Comment by Shahor** [comment] 2019-04-02 17:16
I can confirm I get the same error as well when delivering notifications and most of them are being delivered.

**Comment by zardilior** [comment] 2019-04-09 15:52
I had this error when sending notifications to devices that did not contain the app any longer

**Comment by zardilior** [comment] 2019-04-09 15:52
Or where the app had an error

**Comment by EricCronje** [comment] 2019-04-18 07:41
Hi, might be related. Had the same issue. But with me it was the setup of the target to deploy to multiple sites that was setup incorrectly. Added to the hosting - the target URL instead of the firebase hosting identifier.

firebase target:apply hosting <InstanceName> <URL>

Instead of:

firebase target:apply hosting <InstanceName> <Instance ID on firebase hosting to the site>

After running deploy - it worked then.

**Comment by pocheshire** [comment] 2019-05-15 08:03
Got the same issue when trying to send a notification. The app is installed and push token also has been recently updated.

```
{ Error: Requested entity was not found.
    at FirebaseMessagingError.FirebaseError [as constructor] (/srv/node_modules/firebase-admin/lib/utils/error.js:42:28)
    at FirebaseMessagingError.PrefixedFirebaseError [as constructor] (/srv/node_modules/firebase-admin/lib/utils/error.js:88:28)
    at new FirebaseMessagingError (/srv/node_modules/firebase-admin/lib/utils/error.js:253:16)
    at Function.FirebaseMessagingError.fromServerError (/srv/node_modules/firebase-admin/lib/utils/error.js:283:16)
    at Object.createFirebaseError (/srv/node_modules/firebase-admin/lib/messaging/messaging-errors.js:34:47)
    at /srv/node_modules/firebase-admin/lib/messaging/messaging-api-request.js:76:42
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
  errorInfo: 
   { code: 'messaging/registration-token-not-registered',
     message: 'Requested entity was not found.' },
  codePrefix: 'messaging' }
```

**Comment by searchy2** [comment] 2019-06-07 16:26
I'm experiencing this issue too. Push notifications tokens are reported as invalid after the user uninstalls the app and Firebase Admin throws the error.
```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://fcm.googleapis.com/v1/projects/fabrictools-de669/messages:send

   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1832, in full_dispatch_request
     rv = self.dispatch_request()
   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1818, in dispatch_request
     return self.view_functions[rule.endpoint](**req.view_args)
   File "/app/nocd/app.py", line 1413, in moderator_push_notification_send
     utils.send_notifications(ios_messages, fcm_messages)
   File "/app/nocd/utils.py", line 428, in send_notifications
     send_fcm_notifications(fcm_notifications)
   File "/app/nocd/utils.py", line 444, in send_fcm_notifications
     response = messaging.send(notification)
   File "/usr/local/lib/python3.6/dist-packages/firebase_admin/messaging.py", line 100, in send
     return _get_messaging_service(app).send(message, dry_run)
   File "/usr/local/lib/python3.6/dist-packages/firebase_admin/messaging.py", line 371, in send
     self._handle_fcm_error(error)
   File "/usr/local/lib/python3.6/dist-packages/firebase_admin/messaging.py", line 472, in _handle_fcm_error
     raise ApiCallError(code, msg, error)
 firebase_admin.messaging.ApiCallError: Requested entity was not found.
```
This issue should probably be reopened.

**Comment by hiranya911** [comment] 2019-06-07 17:02
> Push notifications tokens are reported as invalid after the user uninstalls the app and Firebase Admin throws the error.

But isn't that the intended behavior?

**Comment by searchy2** [comment] 2019-06-07 17:09
Throwing an exception crashes the app and causes subsequent notifications to not be sent. Is there a recommended way to handle this situation? Perhaps catch the exception and match an error code?

**Comment by hiranya911** [comment] 2019-06-07 17:35
Yes, naturally. The `send()` method can fail due to a whole host of reasons, so developers should always catch the `messaging.ApiCallError`. This has a `code` property which in this case is probably getting set to `registration-token-not-registered`.

**Comment by searchy2** [comment] 2019-06-07 18:11
Great! Thanks for answering those questions. I'll catch the error and handle the error in the exception!

**Comment by zardilior** [comment] 2019-06-07 23:44
Thanks @hiranya911

**Comment by ShakunthalaMK** [comment] 2019-07-30 13:34
We observed this when the apply plugin was not set in build.gradle of android app.

**Comment by TimelyManner** [comment] 2019-08-05 02:07
I observed a similar issue as well.

**Comment by weitieda** [comment] 2019-08-08 02:16
Few hours ago, notification pushed and received successfully... but without changing any cloud function code, after few hours, it gave me `Requested entity was not found` error... no idea why... (using `Node.js`)

**Comment by redcomethk** [comment] 2019-08-17 10:59
I observed a similar issue as well. The fcm message was sent to one user but not the other. For the one failed to sent to the other user, the same error was observed.
I guess it's because the other user's fcm token was not valid anymore and so this error was returned.

**Comment by h-amg** [comment] 2019-09-08 17:07
this error occurs when the messaging token is invalid

**Comment by NaNtrack** [comment] 2020-05-05 02:32
check that you're using the absolute path to the json provided from firebase when you are configuring the notification factory, that works for me.

**Comment by zardilior** [comment] 2020-05-07 22:51
Honestly the error is not clear at all if the case is what @h-amg says, should be corrected

**Comment by hiranya911** [comment] 2020-05-07 23:37
Can somebody open a new issue for this please? The original report is pretty old and most of it no longer applies to how the SDK works these days. Please specify the SDK version and some sample code/steps to reproduce.

**Comment by hiranya911** [comment] 2020-05-07 23:37
My main concern is with this:

```
firebase_admin.messaging.ApiCallError: Requested entity was not found.
```

That's not a type that exists any more. So this must be a pretty old version of the SDK.

**Comment by zardilior** [comment] 2020-05-08 12:53
@hiranya911  so it does not exist anymore?

**Comment by hiranya911** [comment] 2020-05-08 16:39
That particular type `ApiCallError` was removed with v3 release.

**Comment by myke-awoniran** [comment] 2024-09-10 20:30
Facing this error in 2024, any help @hiranya911 ?

FirebaseMessagingError: Requested entity was not found.

    at FirebaseMessagingError.fromServerError (/home/app/node_modules/firebase-admin/lib/utils/error.js:254:16)

    at createFirebaseError (/home/app/node_modules/firebase-admin/lib/messaging/messaging-errors-internal.js:35:47)

    at /home/app/node_modules/firebase-admin/lib/messaging/messaging-api-request-internal.js:79:75

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {

  errorInfo: {

    code: 'messaging/registration-token-not-registered',

    message: 'Requested entity was not found.'

  },

  codePrefix: 'messaging'

}
