### ISSUE TITLE
FR: Implement Retry for HTTP 502

### ISSUE THREAD

**Issue by dhaval-mehta** [firebase/firebase-admin-python#493] opened 2020-09-25 20:47 UTC
* Operating System version: Ubuntu 16.04 LTS
  * Firebase SDK version: 4.3.0
  * Firebase Product: Push Notification
  * Python Version: 3.8.5 

### Describe the problem

Got error while sending Push Notification

```Unexpected HTTP response with status: 502; body: <!DOCTYPE HTML>...```

#### Steps to reproduce:

Happens randomly on the Production Server.

### Possible Solution:

Implement retry When the Server responds with HTTP 502.

## Trace:

```python
HTTPError: 502 Server Error: Bad Gateway for url: https://fcm.googleapis.com/v1/projects/betterhalf-v2/messages:send
  File "firebase_admin/messaging.py", line 348, in send
    resp = self._client.body(
  File "firebase_admin/_http_client.py", line 129, in body
    resp = self.request(method, url, **kwargs)
  File "firebase_admin/_http_client.py", line 117, in request
    resp.raise_for_status()
  File "requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
UnknownError: Unexpected HTTP response with status: 502; body: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 502 (Server Error)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>502.</b> <ins>That’s an error.</ins>
  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That’s all we know.</ins>
```

**Comment by hiranya911** [comment] 2020-09-25 20:51
This is not a normal error condition. @chong-shao can you take a look? Seems the FCM backend service is experiencing some issue.

As for retries, we can only return 503 and certain 500 errors (as per https://cloud.google.com/apis/design/errors#error_retries). Also the above error message says "try again in 30 seconds". So an automated retry is not really feasible.

**Comment by chong-shao** [comment] 2020-10-13 18:44
It's hard to tell what the issue is given the provided information. But if the time occurred on Sep. 25 this might be due to the outage that had large impact on that day. 

Is the error still happening?

**Comment by stasnovogursky** [comment] 2020-10-23 08:11
My production server's hosted in Azure and it has been experiencing the same problem since begging of October 2020...
There were several periods in hour or two when on staging it worked properly even without retry.
My current retry policy is 2-4-8-16-32 seconds but still no luck! And it doesn't mean that sum delay ~ 62+ sec, FCM replies with 502 in seconds! up to 20-30 seconds, so real delay could be minutes!

**Comment by hiranya911** [comment] 2020-12-02 23:09
I'm going to close this as I cannot see any immediate action items for this repo. 502 is not an error code we wish to implement retries on (developers can implement it on their end using the new error handling APIs, if they wish).

Developers who are seeing these errors in their deployments should contact Firebase Support with more details about their setup, so we can take a look from the FCM backend to see what's going on.

**Closed by hiranya911** 2020-12-02 23:09 UTC
Labels: api: messaging, type: feature request
